title: blueHTPC
description: blueHTPC is a custom operating system meant to be your new TV.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/douglascdev/blueHTPC
  iso_url: https://github.com/douglascdev/blueHTPC/releases
  repository_name: blueHTPC
  owner_url: https://github.com/douglascdev
  owner_name: douglascdev
